### ISSUE TITLE
Retrieve sell order is unauthorized

### ISSUE THREAD

**Issue by jestillore** [IonicaBizau/coins-ph#18] opened 2018-02-09 10:07 UTC
Hi. Thanks for this wonderful package. I have an issue with retrieving sell order. It always turns 401. Here's how I do it.
```js
const Coins = require("coins-ph")

let client = new Coins({
  key: 'KEY',
  secret: 'SECRET'
})

client.sellorder({sellorder_id: '1o2r3d4e5r'}, (err, data) => {
  console.log('data', data)
})
```
I always got this response:
```json
{
  "message": "Unauthorized",
  "status": 401,
  "success": false
}
```
However, the issue is nonexistent for `createSellorder`.

**Comment by IonicaBizau** [comment] 2018-02-11 08:41
I can definitely see something wrong in the code: I think `data: "orders"` should not be passed here. Can you try deleting that property (in the `node_modules/coins-ph/lib/index.js`) and see if that fixes the issue? If so, please create a PR.

https://github.com/IonicaBizau/coins-ph/blob/09ad0ec212b6fa454cbc5e87387d6f27a67922b2/lib/index.js#L132-L136

Also, something similar in the `transactionHistory`:

https://github.com/IonicaBizau/coins-ph/blob/09ad0ec212b6fa454cbc5e87387d6f27a67922b2/lib/index.js#L148-L155

**Comment by jestillore** [comment] 2018-02-12 05:11
I tried deleting the property but the problem is still there.

**Comment by jestillore** [comment] 2018-02-21 05:42
Any update on this?

**Comment by IonicaBizau** [comment] 2018-08-08 06:23
Can you confirm this is a duplicate of https://github.com/IonicaBizau/coins-ph/issues/19?

Maybe this is only for business accounts.

**Comment by imjeffparedes** [comment] 2018-09-27 02:03
@IonicaBizau  Yes but No. They haven't addressed the issue. I used Oath Auth for a while so I closed the issue. Then I tried HMAC Auth manually and it worked.
There is something wrong with this package. 
Here is the header generator for each of my requests required by HMAC Auth :

```
var moment = require('moment');
var rp     = require('request-promise');
const crypto = require('crypto');

var getHmacHeaders = function(data){
    var nonce = (moment().valueOf()* 1e126).toString();
    var message = nonce + data.uri + (data.body? JSON.stringify(data.body):"");
    const hmac = crypto.createHmac('sha256', config.coinsph.API_SECRET);
    hmac.update(message);
    var signature = hmac.digest('hex');
    data.headers = 
            {
                'Accept': 'application/json', 
                'Content-Type': 'application/json',
                'ACCESS_KEY': config.coinsph.API_KEY,
                'ACCESS_SIGNATURE': signature,
                'ACCESS_NONCE': nonce
            }
    return data;
}

```

Using **data.headers** as headers for each of your request will solve your 401 Unauthorized issue.

**Comment by imjeffparedes** [comment] 2018-09-27 04:09
So I found out that the nonce is too low. I used mine 1e126 instead of 1e13. Pull request submitted :)

**Comment by IonicaBizau** [comment] 2018-09-27 13:10
@imjeffparedes Can you check if the issue is fixed now? 😁 Thanks again!

**Comment by imjeffparedes** [comment] 2018-09-27 13:38
@IonicaBizau Retrieve sell order is working now. 👍

**Comment by imjeffparedes** [comment] 2018-12-07 03:30
⚠️ I just want to inform everyone that your next  **nonce**  should be **greater** that the **nonce** from your **last request** .

**Comment by imjeffparedes** [comment] 2018-12-07 03:32
Will have to add option to set the nonce multiplier.

**Comment by IonicaBizau** [comment] 2018-12-07 14:55
But `getTime` will always return a greater number.

**Comment by imjeffparedes** [comment] 2018-12-08 06:55
@IonicaBizau Indeed but If they accidentally tried a bigger nonce before and that the generated nonce of this library is less than that nonce, then all their request will be unauthorized. 
That is what happened to me and @jestillore .

**Comment by IonicaBizau** [comment] 2018-12-10 13:19
Well, in that case I guess one can override the nonce function with a custom implementation.

**Closed as completed** 2018-12-31 12:01 UTC
